export default {
  SIGNUP_URL: '/users/auth/signUp',
  VERIFY_OTP_URL: '/users/auth/verify-pin',
  RESEND_OTP_URL_RESET: '/users/auth/resend-code/reset',
  RESEND_OTP_URL_VERIFY: '/users/auth/resend-code/verify',
  FORGET_PASS_URL: '/users/auth/forget-password',
  SIGNIN_URL: '/users/auth/login',
  VERIFY_UNSERNAME_URL: '/users/auth/checkusername',
  UPDATE_PASSWORD_URL: '/users/auth/reset-password',
  UPDATE_PASS_USER: '/users/update-password',
  GET_USER_URL: '/users/user',
  UPDATE_USER_URL: '/users',
  IMAGE_URL: 'http://3.142.47.134:3000',
  PROD_IMAGE_URL: 'http://3.142.47.134:3000/api/v1/products',
  Products_URL: '/products',
  ORDER_URL: '/orders/order',
  ORDER_HISTORY: '/orders/history',
  FEATURED_PRODUCT: '/products/featured',
  SEARCH_PRODUCTS: '/products/product',
  GET_ALL_ORDERS: '/orders',
  GET_ALL_CONSIGNMENTS: '/consignments',
  GET_ALL_VEHICLES: '/vehicles',
  CREATE_CONSIGNMENTS: '/consignments/new',
  GET_ALL_FEATURED_PRODUCTS: '/products/featured',
  GET_ALL_PRODUCTS: '/products',
  GET_ALL_CATAGORIES: '/categories',
  GET_ALL_NOTIFICATION: '/notifications',
};
